#pragma once

#define SIUDEMKA_WIDTH 384
#define SIUDEMKA_HEIGHT 216
#define UI_HEIGHT 320
#define AUTHOR_HEIGHT 48

#define ALL_HEIGHT (SIUDEMKA_HEIGHT + UI_HEIGHT)
#define UI_OFFCENTER (UI_HEIGHT - SIUDEMKA_HEIGHT)

#define WINDOW_MIN_WIDTH SIUDEMKA_WIDTH
#define WINDOW_MIN_HEIGHT (ALL_HEIGHT + AUTHOR_HEIGHT)
#define WINDOW_MO_HEIGHT (SIUDEMKA_HEIGHT + AUTHOR_HEIGHT)